version: "3.8"

services:
  smart_task_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_task_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8009:9000" # Memetakan port 8009 di VPS ke port 9000 PHP-FPM di dalam container
    environment:
      - REVERB_HOST=smart_task_reverb
    networks:
      - costume_shared_net

  smart_task_reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_task_reverb
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8080:8080" # Memetakan port 8080 Reverb ke host
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    networks:
      - costume_shared_net

networks:
  costume_shared_net:
    external: true
    name: shared-network
