version: "3.8"

services:
  smart_task_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_task_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8009:9000" # Memetakan port 8009 di VPS ke port 9000 PHP-FPM di dalam container
    networks:
      - costume_shared_net

networks:
  costume_shared_net:
    external: true
    name: shared-network
